// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

var BookItems = {};

var Book = {};

var Author = {};

var BookLendings = {};

function authorNames(cat, book) {
  return Belt_Array.map(book.authorIds, (function (x) {
                return Belt_Option.getExn(Belt_MapString.get(cat.authorsById, x)).name;
              }));
}

var BookInfo = {};

function bookInfo(cat, book) {
  return {
          title: book.title,
          isbn: book.isbn,
          authorNames: authorNames(cat, book)
        };
}

function searchBooksByTitle(cat, query) {
  return Belt_MapString.valuesToArray(Belt_MapString.map(Belt_MapString.keep(cat.booksByIsbn, (function (param, v) {
                        return v.title.includes(query);
                      })), (function (v) {
                    return bookInfo(cat, v);
                  })));
}

exports.BookItems = BookItems;
exports.Book = Book;
exports.Author = Author;
exports.BookLendings = BookLendings;
exports.authorNames = authorNames;
exports.BookInfo = BookInfo;
exports.bookInfo = bookInfo;
exports.searchBooksByTitle = searchBooksByTitle;
/* No side effect */
