// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var BookItems = {};

var Book = {};

var Author = {};

var BookLendings = {};

var watchmen_authors = [
  "alan-moore",
  "dave-gibbons"
];

var watchmen_bookItems = [
  {
    id: "book-item-1",
    rackId: "rack-17",
    isLent: true
  },
  {
    id: "book-item-2",
    rackId: "rack-17",
    isLent: false
  }
];

var watchmen = {
  title: "Watchmen",
  publicationYear: 1987,
  isbn: "978-1779501127",
  authors: watchmen_authors,
  bookItems: watchmen_bookItems
};

exports.BookItems = BookItems;
exports.Book = Book;
exports.Author = Author;
exports.BookLendings = BookLendings;
exports.watchmen = watchmen;
/* No side effect */
