// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_MapString = require("rescript/lib/js/belt_MapString.js");
var Catalog$AdventOfCode = require("./Catalog.bs.js");

var watchmen_authorIds = [
  "alan-moore",
  "dave-gibbons"
];

var watchmen_bookItems = [
  {
    id: "book-item-1",
    rackId: "rack-17",
    isLent: true
  },
  {
    id: "book-item-2",
    rackId: "rack-17",
    isLent: false
  }
];

var watchmen = {
  title: "Watchmen",
  publicationYear: 1987,
  isbn: "978-1779501127",
  authorIds: watchmen_authorIds,
  bookItems: watchmen_bookItems
};

var sampleCatalog_booksByIsbn = Belt_MapString.set(undefined, "978-1779501127", {
      title: "Watchmen",
      publicationYear: 1987,
      isbn: "978-1779501127",
      authorIds: [
        "alan-moore",
        "dave-gibbons"
      ],
      bookItems: [
        {
          id: "book-item-1",
          rackId: "rack-17",
          isLent: true
        },
        {
          id: "book-item-2",
          rackId: "rack-17",
          isLent: false
        }
      ]
    });

var sampleCatalog_authorsById = Belt_MapString.set(Belt_MapString.set(undefined, "alan-moore", {
          name: "Alan Moore",
          bookIsbns: ["978-1779501127"]
        }), "dave-gibbons", {
      name: "Dave Gibbons",
      bookIsbns: ["978-1779501127"]
    });

var sampleCatalog = {
  booksByIsbn: sampleCatalog_booksByIsbn,
  authorsById: sampleCatalog_authorsById
};

function log(prim) {
  console.log(prim);
  
}

var r = Catalog$AdventOfCode.authorNames(sampleCatalog, watchmen);

console.log("authorNames");

console.log(r);

var bi = Catalog$AdventOfCode.bookInfo(sampleCatalog, watchmen);

console.log("bookInfo");

console.log(bi);

var s1 = Catalog$AdventOfCode.searchBooksByTitle(sampleCatalog, "danny");

console.log("searchBooksByTitle s1");

console.log(s1);

var s2 = Catalog$AdventOfCode.searchBooksByTitle(sampleCatalog, "tch");

console.log("searchBooksByTitle s2");

console.log(s2);

exports.watchmen = watchmen;
exports.sampleCatalog = sampleCatalog;
exports.log = log;
exports.r = r;
exports.bi = bi;
exports.s1 = s1;
exports.s2 = s2;
/* sampleCatalog Not a pure module */
