// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

var watchmen_authorIds = [
  "alan-moore",
  "dave-gibbons"
];

var watchmen_bookItems = [
  {
    id: "book-item-1",
    rackId: "rack-17",
    isLent: true
  },
  {
    id: "book-item-2",
    rackId: "rack-17",
    isLent: false
  }
];

var watchmen = {
  title: "Watchmen",
  publicationYear: 1987,
  isbn: "978-1779501127",
  authorIds: watchmen_authorIds,
  bookItems: watchmen_bookItems
};

var sampleCatalog_booksByIsbn = Belt_MapString.set(undefined, "978-1779501127", {
      title: "Watchmen",
      publicationYear: 1987,
      isbn: "978-1779501127",
      authorIds: [
        "alan-moore",
        "dave-gibbons"
      ],
      bookItems: [
        {
          id: "book-item-1",
          rackId: "rack-17",
          isLent: true
        },
        {
          id: "book-item-2",
          rackId: "rack-17",
          isLent: false
        }
      ]
    });

var sampleCatalog_authorsById = Belt_MapString.set(Belt_MapString.set(undefined, "alan-moore", {
          name: "Alan Moore",
          bookIsbns: ["978-1779501127"]
        }), "dave-gibbons", {
      name: "Dave Gibbons",
      bookIsbns: ["978-1779501127"]
    });

var sampleCatalog = {
  booksByIsbn: sampleCatalog_booksByIsbn,
  authorsById: sampleCatalog_authorsById
};

var userManagementData_librarians = Belt_MapString.set(undefined, "franck@gmail.com", {
      email: "franck@gmail.com",
      encryptedPassword: "bXlwYXNzd29yZA=="
    });

var userManagementData_members = Belt_MapString.set(undefined, "samantha@gmail.com", {
      email: "samantha@gmail.com",
      encryptedPassword: "c2VjcmV0",
      isBlocked: false,
      bookLendings: [{
          bookItemId: "book-item-1",
          bookIsbn: "978-1779501127",
          lendingDate: "2020-04-23"
        }]
    });

var userManagementData = {
  librarians: userManagementData_librarians,
  members: userManagementData_members
};

var libraryData = {
  name: "The smallest library on earth",
  address: "Here and now",
  catalog: sampleCatalog,
  userManagement: userManagementData
};

exports.watchmen = watchmen;
exports.sampleCatalog = sampleCatalog;
exports.userManagementData = userManagementData;
exports.libraryData = libraryData;
/* sampleCatalog Not a pure module */
