// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Catalog$AdventOfCode = require("./Catalog.bs.js");
var Library$AdventOfCode = require("./Library.bs.js");
var Example_Data$AdventOfCode = require("./Example_Data.bs.js");

function log(prim) {
  console.log(prim);
  
}

var r = Catalog$AdventOfCode.authorNames(Example_Data$AdventOfCode.sampleCatalog, Example_Data$AdventOfCode.watchmen);

console.log("authorNames");

console.log(r);

var bi = Catalog$AdventOfCode.bookInfo(Example_Data$AdventOfCode.sampleCatalog, Example_Data$AdventOfCode.watchmen);

console.log("bookInfo");

console.log(bi);

var s1 = Catalog$AdventOfCode.searchBooksByTitle(Example_Data$AdventOfCode.sampleCatalog, "danny");

console.log("searchBooksByTitle s1");

console.log(s1);

var s2 = Catalog$AdventOfCode.searchBooksByTitle(Example_Data$AdventOfCode.sampleCatalog, "tch");

console.log("searchBooksByTitle s2");

console.log(s2);

var s3 = Library$AdventOfCode.searchBooksByTitleJSON(Example_Data$AdventOfCode.libraryData, "tch");

console.log("searchBooksByTitleJSON s3");

console.log(s3);

exports.log = log;
exports.r = r;
exports.bi = bi;
exports.s1 = s1;
exports.s2 = s2;
exports.s3 = s3;
/* r Not a pure module */
