// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Catalog$AdventOfCode = require("./Catalog.bs.js");

function searchBooksByTitleJSON(library, query) {
  return JSON.stringify(Catalog$AdventOfCode.searchBooksByTitle(library.catalog, query));
}

exports.searchBooksByTitleJSON = searchBooksByTitleJSON;
/* No side effect */
