// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_exn = require("rescript/lib/js/js_exn.js");
var Library$DopRescript = require("./Library.bs.js");
var Example_Data$DopRescript = require("./Example_Data.bs.js");

function get(t) {
  return t.systemState;
}

function validate(previous, next) {
  return {
          TAG: /* Ok */0,
          _0: next
        };
}

function commit(previous, next) {
  var s = {
    TAG: /* Ok */0,
    _0: next
  };
  if (s.TAG === /* Ok */0) {
    return {
            systemState: next
          };
  }
  throw Js_exn.raiseError(next);
}

function make(library) {
  return {
          systemState: library
        };
}

var SystemState = {
  get: get,
  validate: validate,
  commit: commit,
  make: make
};

var globalState = {
  contents: {
    systemState: Example_Data$DopRescript.libraryData
  }
};

function wrapWithState(f, arg1) {
  var previous = globalState.contents.systemState;
  var next = Curry._2(f, previous, arg1);
  var __x = globalState.contents;
  globalState.contents = commit(__x, next);
  
}

function addMember(member) {
  return wrapWithState(Library$DopRescript.addMember, member);
}

exports.SystemState = SystemState;
exports.globalState = globalState;
exports.wrapWithState = wrapWithState;
exports.addMember = addMember;
/* Example_Data-DopRescript Not a pure module */
