// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

var Users = {};

var BookLending = {};

var Member = {};

var Librarian = {};

function isVIPMember(userManagement, email) {
  return Belt_Option.getExn(Belt_MapString.get(userManagement.membersByEmail, email)).isVIP;
}

function isSuperMember(userManagement, email) {
  return Belt_Option.getExn(Belt_MapString.get(userManagement.membersByEmail, email)).isSuper;
}

exports.Users = Users;
exports.BookLending = BookLending;
exports.Member = Member;
exports.Librarian = Librarian;
exports.isVIPMember = isVIPMember;
exports.isSuperMember = isSuperMember;
/* No side effect */
