// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

var Users = {};

var BookLending = {};

var Member = {};

var Librarian = {};

function isVIPMember(userManagement, email) {
  return Belt_Option.getExn(Belt_MapString.get(userManagement.membersByEmail, email)).isVIP;
}

function isSuperMember(userManagement, email) {
  return Belt_Option.getExn(Belt_MapString.get(userManagement.membersByEmail, email)).isSuper;
}

function addMember(userManagement, member) {
  var __x = userManagement.membersByEmail;
  var u = Belt_MapString.get(__x, member.email);
  if (u !== undefined) {
    return {
            TAG: /* Error */1,
            _0: /* AlreadyExist */0
          };
  } else {
    return {
            TAG: /* Ok */0,
            _0: {
              librariansByEmail: userManagement.librariansByEmail,
              membersByEmail: Belt_MapString.set(userManagement.membersByEmail, member.email, member)
            }
          };
  }
}

exports.Users = Users;
exports.BookLending = BookLending;
exports.Member = Member;
exports.Librarian = Librarian;
exports.isVIPMember = isVIPMember;
exports.isSuperMember = isSuperMember;
exports.addMember = addMember;
/* No side effect */
